return {
  "catppuccin/nvim",
  name = "catppuccin",
  opts = {
    flavour = "frappe",
    dim_inactive = { enabled = true, percentage = 0.1 },
    integrations = {
      alpha = false,
      dashboard = false,
      nvimtree = false,
      ts_rainbow = false,
      barbecue = false,
      indent_blankline = false,
      navic = false,
      dropbar = false,

      aerial = true,
      dap = { enabled = true, enable_ui = true },
      mason = true,
      native_lsp = { enabled = true, inlay_hints = { background = false } },
      neotree = true,
      noice = true,
      notify = true,
      semantic_tokens = true,
      symbols_outline = true,
      telescope = { enabled = true },
      which_key = true,
    },
    custom_highlights = {
      -- disable italics  for treesitter highlights
      -- TabLineFill = { link = "StatusLine" },
      -- LspInlayHint = { style = { "italic" } },
      -- ["@parameter"] = { style = {} },
      -- ["@type.builtin"] = { style = {} },
      -- ["@namespace"] = { style = {} },
      -- ["@text.uri"] = { style = { "underline" } },
      -- ["@tag.attribute"] = { style = {} },
      -- ["@tag.attribute.tsx"] = { style = {} },
    },
  },
}
